"""Renderer shape checks for what reading the catalog back cannot show.

``test_schema_inspect.py`` proves the DDL is correct; these cover the settings
switches and the spellings PostgreSQL rewrites on the way in.
"""

from __future__ import annotations

import pytest

from pgqueuer.adapters.persistence.schema_ddl import render_install, render_uninstall
from pgqueuer.domain.settings import DBSettings, Durability


def test_install_starts_with_provenance() -> None:
    """The version is not asserted: a source checkout reports 0.0.0."""
    header = render_install(DBSettings(prefix="acme_", db_schema="billing")).splitlines()[0]
    assert header.startswith("-- pgqueuer ")
    assert "prefix='acme_'" in header
    assert "schema='billing'" in header
    assert "durability=durable" in header


def test_serial_and_identity_columns_keep_their_kind() -> None:
    install = render_install(DBSettings())
    assert "    id bigserial NOT NULL PRIMARY KEY," in install
    assert "    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY," in install


def test_unique_constraint_is_rendered_inline() -> None:
    assert "    UNIQUE (expression, entrypoint)" in render_install(DBSettings())


@pytest.mark.parametrize(
    ("durability", "expected"),
    [(Durability.durable, 0), (Durability.balanced, 2), (Durability.volatile, 4)],
)
def test_durability_decides_which_tables_are_unlogged(
    durability: Durability,
    expected: int,
) -> None:
    install = render_install(DBSettings(durability=durability))
    assert install.count("CREATE UNLOGGED TABLE") == expected


def test_schema_qualifies_every_object_and_is_optional() -> None:
    settings = DBSettings(prefix="acme_", db_schema="billing")
    install = render_install(settings)
    assert "CREATE SCHEMA IF NOT EXISTS billing;" in install
    assert "CREATE TABLE billing.acme_pgqueuer (" in install
    assert "CREATE INDEX acme_pgqueuer_ep_ea_idx ON billing.acme_pgqueuer " in install
    assert "CREATE SCHEMA" not in render_install(settings, create_schema=False)


def test_uninstall_drops_dependents_first_and_the_retired_type() -> None:
    lines = render_uninstall(DBSettings()).splitlines()
    assert all(line.startswith("DROP ") for line in lines)
    kinds = [line.split()[1] for line in lines]
    assert kinds == ["TRIGGER", "FUNCTION"] + ["TABLE"] * 4 + ["TYPE"] * 2
    assert "DROP TYPE IF EXISTS pgqueuer_statistics_status;" in lines
