version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
    create_environment:
      # Install UV via asdf and set it up
      - asdf plugin add uv || true
      - asdf install uv latest
      - asdf global uv latest
      - uv venv  # Initialize a UV-managed virtual environment

    install:
      # Use UV to install the documentation dependencies
      - uv sync --frozen --only-group docs

    build:
      html:
        # Build the documentation using Sphinx
        - uv run --only-group docs sphinx-build -T -b html -d _build/doctrees -D language=en docs/ $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
