"""Backward-compatibility shim. Canonical: pgqueuer.adapters.cli.cli"""
from pgqueuer.adapters.cli.cli import (
    AppConfig,
    VerifyMode,
    app,
    create_default_queries_factory,
    dashboard,
    display_pg_channel,
    display_schedule,
    display_stats,
    durability,
    fetch_and_display,
    install,
    listen,
    main,
    optimize_autovacuum,
    queue,
    run,
    schedules,
    uninstall,
    upgrade,
    verify,
    yield_queries,
)

__all__ = [
    "AppConfig",
    "VerifyMode",
    "app",
    "create_default_queries_factory",
    "dashboard",
    "display_pg_channel",
    "display_schedule",
    "display_stats",
    "durability",
    "fetch_and_display",
    "install",
    "listen",
    "main",
    "optimize_autovacuum",
    "queue",
    "run",
    "schedules",
    "uninstall",
    "upgrade",
    "verify",
    "yield_queries",
]
