"""Per-object schema revision markers.

Every database object PgQueuer creates carries a JSON marker in its Postgres
comment naming the schema revision it dates from. The manifest below is the
set of objects the running code requires; comparing it against the catalog at
startup answers "can this code drive this schema" without probing for shapes.
"""

from __future__ import annotations

import json
from typing import Generator, Literal, get_args

import pydantic

from pgqueuer.domain import types
from pgqueuer.domain.settings import DBSettings

# Bumped only when the DDL changes. An object is stamped once, with the
# revision its current shape dates from, and is re-stamped only if the object
# itself is recreated. A bump may only add objects or widen types; anything
# that drops or narrows is a major release. See CONTRIBUTING.md.
SCHEMA_REVISION = 1

# Top-level key in the comment JSON. Namespaced so a foreign directive that
# happens to share the object is at least distinguishable.
MARKER_KEY = "pgqueuer"

# NAMEDATALEN - 1: Postgres stores no identifier longer than this.
POSTGRES_IDENTIFIER_LIMIT = 63

SchemaObjectKind = Literal[
    "table",
    "column",
    "index",
    "type",
    "function",
    "trigger",
    "enum_value",
]

# "advisory" objects only make queries faster; the code runs without them, so
# their absence warns instead of refusing to start.
SchemaObjectSeverity = Literal["required", "advisory"]

SchemaObjectKey = tuple[SchemaObjectKind, str, str | None]


def truncate_identifier(name: str) -> str:
    """*name* as Postgres stores it: clipped to 63 bytes when creating the object."""
    encoded = name.encode()
    if len(encoded) <= POSTGRES_IDENTIFIER_LIMIT:
        return name
    return encoded[:POSTGRES_IDENTIFIER_LIMIT].decode(errors="ignore")


class SchemaObject(pydantic.BaseModel):
    """One entry in the manifest: an object the running code requires.

    ``parent`` is the object this one hangs off -- the table for a column,
    index or trigger, the enum type for an enum value -- and is None for
    schema-level objects. Names are bare; the caller qualifies them.
    """

    model_config = pydantic.ConfigDict(frozen=True)

    kind: SchemaObjectKind
    name: str
    revision: int
    parent: str | None = None
    severity: SchemaObjectSeverity = "required"

    @property
    def key(self) -> SchemaObjectKey:
        return (self.kind, self.name, self.parent)

    @property
    def label(self) -> str:
        """Human-readable identity for error messages."""
        # An index name is unique across the schema, so its table adds noise.
        if self.parent and self.kind != "index":
            return f"{self.kind} '{self.parent}.{self.name}'"
        return f"{self.kind} '{self.name}'"


class SchemaMarker(pydantic.BaseModel):
    """Payload written into an object's comment under MARKER_KEY."""

    model_config = pydantic.ConfigDict(frozen=True)

    schema_revision: int

    def render(self) -> str:
        """Compact JSON for embedding in a SQL literal."""
        return json.dumps({MARKER_KEY: self.model_dump()}, separators=(",", ":"))


def parse_marker(comment: str | None) -> int | None:
    """Revision recorded in *comment*, or None when it says nothing usable.

    Never raises. Object comments are user-writable, so every malformed shape
    -- absent, not JSON, JSON that is not an object, missing key, non-integer
    revision -- has to resolve to "unknown" rather than an exception on the
    worker startup path. Strict validation is what rejects a bool, which would
    otherwise pass as the int subclass it is.
    """
    if not comment:
        return None
    try:
        document = json.loads(comment)
    except (ValueError, RecursionError):
        # Deeply nested JSON exhausts the C stack rather than failing to parse.
        return None
    if not isinstance(document, dict):
        return None
    block = document.get(MARKER_KEY)
    if not isinstance(block, dict):
        return None
    try:
        return SchemaMarker.model_validate(block, strict=True).schema_revision
    except pydantic.ValidationError:
        return None


def manifest(settings: DBSettings) -> tuple[SchemaObject, ...]:
    """Objects the running code requires, each stamped with the revision it dates from.

    Built per call: every name depends on prefix/db_schema. Implicit objects
    are deliberately absent -- primary-key and UNIQUE-constraint indexes and
    the identity sequences cannot exist without their table, and their names
    are generated by Postgres rather than by us.
    """

    def table(revision: int, name: str, *columns: str) -> Generator[SchemaObject, None, None]:
        table_name = truncate_identifier(name)
        yield SchemaObject(kind="table", name=table_name, revision=revision)
        for column in columns:
            yield SchemaObject(
                kind="column",
                name=truncate_identifier(column),
                parent=table_name,
                revision=revision,
            )

    def indexes(
        revision: int,
        parent: str,
        *names: str,
        severity: SchemaObjectSeverity = "advisory",
    ) -> Generator[SchemaObject, None, None]:
        for name in names:
            yield SchemaObject(
                kind="index",
                name=truncate_identifier(name),
                parent=truncate_identifier(parent),
                revision=revision,
                severity=severity,
            )

    status_type = truncate_identifier(settings.queue_status_type)

    return (
        *table(
            1,
            settings.queue_table,
            "id",
            "priority",
            "queue_manager_id",
            "created",
            "updated",
            "heartbeat",
            "execute_after",
            "status",
            "entrypoint",
            "dedupe_key",
            "payload",
            "headers",
            "attempts",
        ),
        *indexes(
            1,
            settings.queue_table,
            f"{settings.queue_table}_priority_id_id1_idx",
            f"{settings.queue_table}_updated_id_id1_idx",
            f"{settings.queue_table}_heartbeat_id_id1_idx",
            f"{settings.queue_table}_queue_manager_id_idx",
            f"{settings.queue_table}_ep_prio_id_idx",
            f"{settings.queue_table}_ep_ea_idx",
        ),
        # Backs the dedupe ON CONFLICT arbiter: without it enqueue fails outright.
        *indexes(
            1,
            settings.queue_table,
            f"{settings.queue_table}_unique_dedupe_key",
            severity="required",
        ),
        *table(
            1,
            settings.queue_table_log,
            "id",
            "created",
            "job_id",
            "status",
            "priority",
            "entrypoint",
            "traceback",
            "aggregated",
        ),
        *indexes(
            1,
            settings.queue_table_log,
            f"{settings.queue_table_log}_not_aggregated",
            f"{settings.queue_table_log}_created",
            f"{settings.queue_table_log}_status",
            f"{settings.queue_table_log}_job_id_status",
        ),
        *table(
            1,
            settings.statistics_table,
            "id",
            "created",
            "count",
            "priority",
            "status",
            "entrypoint",
        ),
        # Backs the statistics ON CONFLICT arbiter.
        *indexes(
            1,
            settings.statistics_table,
            f"{settings.statistics_table}_unique_count",
            severity="required",
        ),
        *table(
            1,
            settings.schedules_table,
            "id",
            "expression",
            "entrypoint",
            "heartbeat",
            "created",
            "updated",
            "next_run",
            "last_run",
            "status",
        ),
        SchemaObject(kind="type", name=status_type, revision=1),
        *(
            SchemaObject(kind="enum_value", name=value, parent=status_type, revision=1)
            for value in sorted(get_args(types.JOB_STATUS))
        ),
        SchemaObject(kind="function", name=truncate_identifier(settings.function), revision=1),
        SchemaObject(
            kind="trigger",
            name=truncate_identifier(settings.trigger),
            parent=truncate_identifier(settings.queue_table),
            revision=1,
        ),
    )


class ObservedObject(pydantic.BaseModel):
    """One row of what the catalog actually holds."""

    model_config = pydantic.ConfigDict(frozen=True)

    kind: SchemaObjectKind
    name: str
    parent: str | None = None
    comment: str | None = None

    @property
    def key(self) -> SchemaObjectKey:
        return (self.kind, self.name, self.parent)


class SchemaNotInstalled(pydantic.BaseModel):
    """The queue table is absent; nothing else was worth checking."""

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["not_installed"] = "not_installed"
    queue_table: str


class SchemaIncomplete(pydantic.BaseModel):
    """Objects the code requires are missing from the database."""

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["incomplete"] = "incomplete"
    missing: tuple[SchemaObject, ...]


class SchemaUsable(pydantic.BaseModel):
    """Every required object is present.

    ``unstamped`` counts objects carrying no readable marker: a pre-1.4
    install, which is usable but should run ``pgq upgrade`` to record its
    revision. ``ahead`` names objects stamped newer than this code -- the
    normal mid-rollout state, since a revision bump may only add objects.
    ``degraded`` holds absent advisory objects, which cost performance rather
    than correctness. ``table_revisions`` is the per-table stamp, for
    `pgq verify` to print.
    """

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["usable"] = "usable"
    unstamped: int = 0
    ahead: tuple[str, ...] = ()
    degraded: tuple[SchemaObject, ...] = ()
    table_revisions: tuple[tuple[str, int | None], ...] = ()


SchemaCheck = SchemaNotInstalled | SchemaIncomplete | SchemaUsable


def root_causes(absent: tuple[SchemaObject, ...]) -> tuple[SchemaObject, ...]:
    """*absent* without the entries explained by an absent ``parent``.

    Nothing hangs off an object that is not there, so listing a dropped
    table's every column and index buries the one fact the operator can act on.
    """
    dropped = {entry.name for entry in absent if entry.kind in ("table", "type")}
    return tuple(entry for entry in absent if entry.parent not in dropped)


def evaluate(
    required: tuple[SchemaObject, ...],
    observed: tuple[ObservedObject, ...],
    queue_table: str,
) -> SchemaCheck:
    """Decide whether the code behind *required* can drive the observed schema.

    Existence is checked independently of the markers, which is what lets a
    pre-1.4 install keep running: it is missing every comment but no object.
    """
    catalog = {item.key: item for item in observed}
    if ("table", truncate_identifier(queue_table), None) not in catalog:
        return SchemaNotInstalled(queue_table=queue_table)

    absent = root_causes(tuple(entry for entry in required if entry.key not in catalog))
    if missing := tuple(entry for entry in absent if entry.severity == "required"):
        return SchemaIncomplete(missing=missing)

    stamps = [
        (entry, parse_marker(catalog[entry.key].comment))
        for entry in required
        if entry.kind != "enum_value" and entry.key in catalog
    ]
    return SchemaUsable(
        degraded=absent,
        unstamped=sum(1 for _, revision in stamps if revision is None),
        ahead=tuple(
            sorted(
                entry.name
                for entry, revision in stamps
                if revision is not None and revision > SCHEMA_REVISION
            )
        ),
        table_revisions=tuple(
            sorted((entry.name, revision) for entry, revision in stamps if entry.kind == "table")
        ),
    )
