"""Per-object schema revision markers.

Every database object PgQueuer creates carries a JSON marker in its Postgres
comment naming the schema revision it dates from. The manifest below is the
set of objects the running code requires; comparing it against the catalog at
startup answers "can this code drive this schema" without probing for shapes.
"""

from __future__ import annotations

import json
from typing import Generator, Literal

import pydantic

from pgqueuer.domain.settings import DBSettings

# Bumped only when the DDL changes. An object is stamped once, with the
# revision its current shape dates from, and is re-stamped only if the object
# itself is recreated. A bump may only add objects or widen types; anything
# that drops or narrows is a major release. See CONTRIBUTING.md.
SCHEMA_REVISION = 1

# Top-level key in the comment JSON. Namespaced so a foreign directive that
# happens to share the object is at least distinguishable.
MARKER_KEY = "pgqueuer"

SchemaObjectKind = Literal[
    "table",
    "column",
    "index",
    "type",
    "function",
    "trigger",
    "enum_value",
]

SchemaObjectKey = tuple[SchemaObjectKind, str, str | None]


class SchemaObject(pydantic.BaseModel):
    """One entry in the manifest: an object the running code requires.

    ``parent`` is the object this one hangs off -- the table for a column or
    trigger, the enum type for an enum value -- and is None for schema-level
    objects. Names are bare; the caller qualifies them.
    """

    model_config = pydantic.ConfigDict(frozen=True)

    kind: SchemaObjectKind
    name: str
    parent: str | None = None
    revision: int = SCHEMA_REVISION

    @property
    def key(self) -> SchemaObjectKey:
        return (self.kind, self.name, self.parent)

    @property
    def label(self) -> str:
        """Human-readable identity for error messages."""
        if self.parent:
            return f"{self.kind} '{self.parent}.{self.name}'"
        return f"{self.kind} '{self.name}'"


class SchemaMarker(pydantic.BaseModel):
    """Payload written into an object's comment under MARKER_KEY."""

    model_config = pydantic.ConfigDict(frozen=True)

    schema_revision: int

    def render(self) -> str:
        """Compact JSON for embedding in a SQL literal."""
        return json.dumps({MARKER_KEY: self.model_dump()}, separators=(",", ":"))


def parse_marker(comment: str | None) -> int | None:
    """Revision recorded in *comment*, or None when it says nothing usable.

    Never raises. Object comments are user-writable, so every malformed shape
    -- absent, not JSON, JSON that is not an object, missing key, non-integer
    revision -- has to resolve to "unknown" rather than an exception on the
    worker startup path. Strict validation is what rejects a bool, which would
    otherwise pass as the int subclass it is.
    """
    if not comment:
        return None
    try:
        document = json.loads(comment)
    except ValueError:
        return None
    if not isinstance(document, dict):
        return None
    block = document.get(MARKER_KEY)
    if not isinstance(block, dict):
        return None
    try:
        return SchemaMarker.model_validate(block, strict=True).schema_revision
    except pydantic.ValidationError:
        return None


def manifest(settings: DBSettings) -> tuple[SchemaObject, ...]:
    """Objects the running code requires, each stamped with the revision it dates from.

    Built per call: every name depends on prefix/db_schema. Implicit objects
    are deliberately absent -- primary-key and UNIQUE-constraint indexes and
    the identity sequences cannot exist without their table, and their names
    are generated by Postgres rather than by us.
    """

    def table(name: str, *columns: str) -> Generator[SchemaObject, None, None]:
        yield SchemaObject(kind="table", name=name)
        for column in columns:
            yield SchemaObject(kind="column", name=column, parent=name)

    def indexes(*names: str) -> Generator[SchemaObject, None, None]:
        for name in names:
            yield SchemaObject(kind="index", name=name)

    return (
        *table(
            settings.queue_table,
            "id",
            "priority",
            "queue_manager_id",
            "created",
            "updated",
            "heartbeat",
            "execute_after",
            "status",
            "entrypoint",
            "dedupe_key",
            "payload",
            "headers",
            "attempts",
        ),
        *indexes(
            f"{settings.queue_table}_priority_id_id1_idx",
            f"{settings.queue_table}_updated_id_id1_idx",
            f"{settings.queue_table}_heartbeat_id_id1_idx",
            f"{settings.queue_table}_queue_manager_id_idx",
            f"{settings.queue_table}_ep_prio_id_idx",
            f"{settings.queue_table}_ep_ea_idx",
            f"{settings.queue_table}_unique_dedupe_key",
        ),
        *table(
            settings.queue_table_log,
            "id",
            "created",
            "job_id",
            "status",
            "priority",
            "entrypoint",
            "traceback",
            "aggregated",
        ),
        *indexes(
            f"{settings.queue_table_log}_not_aggregated",
            f"{settings.queue_table_log}_created",
            f"{settings.queue_table_log}_status",
            f"{settings.queue_table_log}_job_id_status",
        ),
        *table(
            settings.statistics_table,
            "id",
            "created",
            "count",
            "priority",
            "status",
            "entrypoint",
        ),
        *indexes(f"{settings.statistics_table}_unique_count"),
        *table(
            settings.schedules_table,
            "id",
            "expression",
            "entrypoint",
            "heartbeat",
            "created",
            "updated",
            "next_run",
            "last_run",
            "status",
        ),
        SchemaObject(kind="type", name=settings.queue_status_type),
        *(
            SchemaObject(kind="enum_value", name=value, parent=settings.queue_status_type)
            for value in (
                "queued",
                "picked",
                "successful",
                "exception",
                "canceled",
                "deleted",
                "failed",
            )
        ),
        SchemaObject(kind="function", name=settings.function),
        SchemaObject(kind="trigger", name=settings.trigger, parent=settings.queue_table),
    )


class ObservedObject(pydantic.BaseModel):
    """One row of what the catalog actually holds."""

    model_config = pydantic.ConfigDict(frozen=True)

    kind: SchemaObjectKind
    name: str
    parent: str | None = None
    comment: str | None = None

    @property
    def key(self) -> SchemaObjectKey:
        return (self.kind, self.name, self.parent)


class SchemaNotInstalled(pydantic.BaseModel):
    """The queue table is absent; nothing else was worth checking."""

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["not_installed"] = "not_installed"
    queue_table: str


class SchemaIncomplete(pydantic.BaseModel):
    """Objects the code requires are missing from the database."""

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["incomplete"] = "incomplete"
    missing: tuple[SchemaObject, ...]


class SchemaUsable(pydantic.BaseModel):
    """Every required object is present.

    ``unstamped`` counts objects carrying no readable marker: a pre-1.4
    install, which is usable but should run ``pgq upgrade`` to record its
    revision. ``ahead`` names objects stamped newer than this code -- the
    normal mid-rollout state, since a revision bump may only add objects.
    ``table_revisions`` is the per-table stamp, for `pgq verify` to print.
    """

    model_config = pydantic.ConfigDict(frozen=True)

    outcome: Literal["usable"] = "usable"
    unstamped: int = 0
    ahead: tuple[str, ...] = ()
    table_revisions: tuple[tuple[str, int | None], ...] = ()


SchemaCheck = SchemaNotInstalled | SchemaIncomplete | SchemaUsable


def evaluate(
    required: tuple[SchemaObject, ...],
    observed: tuple[ObservedObject, ...],
    queue_table: str,
) -> SchemaCheck:
    """Decide whether the code behind *required* can drive the observed schema.

    Existence is checked independently of the markers, which is what lets a
    pre-1.4 install keep running: it is missing every comment but no object.
    """
    catalog = {item.key: item for item in observed}
    if ("table", queue_table, None) not in catalog:
        return SchemaNotInstalled(queue_table=queue_table)

    if missing := tuple(entry for entry in required if entry.key not in catalog):
        return SchemaIncomplete(missing=missing)

    stamps = [
        (entry, parse_marker(catalog[entry.key].comment))
        for entry in required
        if entry.kind != "enum_value"
    ]
    return SchemaUsable(
        unstamped=sum(1 for _, revision in stamps if revision is None),
        ahead=tuple(
            sorted(
                entry.name
                for entry, revision in stamps
                if revision is not None and revision > SCHEMA_REVISION
            )
        ),
        table_revisions=tuple(
            sorted((entry.name, revision) for entry, revision in stamps if entry.kind == "table")
        ),
    )
