name: "Cache Docker Images and Spin Up Container"
description: "A reusable step to cache Docker images and spin up the PostgreSQL container"
runs:
  using: "composite"
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yml', 'test/db/init_db.sh', 'test/db/Dockerfile', 'uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and Run Docker Compose
      shell: bash
      run: docker compose up --build -d pgq
      env:
        DOCKER_BUILDKIT: 1
