name: "Cache Docker Images and Spin Up Container"
description: "A reusable step to cache Docker images and spin up the PostgreSQL container"
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: test/db/Dockerfile
        tags: janbjorge/pgqueuer:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Run Docker Compose
      shell: bash
      run: docker compose up --build -d pgq
      env:
        DOCKER_BUILDKIT: 1
