"""
Database query builder and executor for job queue operations.

This module provides classes and functions to construct and execute SQL queries
related to job queuing, such as installing the necessary database schema,
enqueueing and dequeueing jobs, logging job statuses, and managing job statistics.
It abstracts the SQL details and offers a high-level interface for interacting
with the database in the context of the pgqueuer application.
"""

from __future__ import annotations

import dataclasses
from typing import Generator

from pgqueuer.domain.settings import (
    DBSettings,
    Durability,
    DurabilityPolicy,
    add_prefix,
)
from pgqueuer.domain.types import SortOrder

# Re-export for backward compatibility within the adapter layer
__all__ = [
    "DBSettings",
    "Durability",
    "DurabilityPolicy",
    "QueryBuilderEnvironment",
    "QueryQueueBuilder",
    "QuerySchedulerBuilder",
    "add_prefix",
]


@dataclasses.dataclass
class QueryBuilderEnvironment:
    """
    Setup/teardown environment for executing queries.

    Handles the configuration required for executing SQL queries, ensuring
    consistent settings are applied during setup and teardown operations.
    """

    settings: DBSettings = dataclasses.field(default_factory=DBSettings)

    def build_install_query(self) -> str:
        """
        Generate SQL statements to install the job queue schema.

        Constructs the SQL commands needed to set up the database schema required
        by the job queue system. This includes creating custom ENUM types for statuses,
        creating the queue and statistics tables, defining indexes to optimize queries,
        and setting up triggers and functions for notifications.

        Returns:
            str: A string containing the SQL commands to install the schema.
        """
        durability_policy = self.settings.durability.config

        return f"""CREATE TYPE {self.settings.queue_status_type} AS ENUM ('queued', 'picked', 'successful', 'exception', 'canceled', 'deleted', 'failed');
    CREATE {durability_policy.queue_table} TABLE {self.settings.queue_table} (
        id SERIAL PRIMARY KEY,
        priority INT NOT NULL,
        queue_manager_id UUID,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        execute_after TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        status {self.settings.queue_status_type} NOT NULL,
        entrypoint TEXT NOT NULL,
        dedupe_key TEXT,
        payload BYTEA,
        headers JSONB,
        attempts INT NOT NULL DEFAULT 0
    );
    CREATE INDEX {self.settings.queue_table}_priority_id_id1_idx ON {self.settings.queue_table} (priority ASC, id DESC)
        INCLUDE (id) WHERE status = 'queued';
    CREATE INDEX {self.settings.queue_table}_updated_id_id1_idx ON {self.settings.queue_table} (updated ASC, id DESC)
        INCLUDE (id) WHERE status = 'picked';
    CREATE INDEX {self.settings.queue_table}_queue_manager_id_idx ON {self.settings.queue_table} (queue_manager_id)
        WHERE queue_manager_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS {self.settings.queue_table}_unique_dedupe_key ON
        {self.settings.queue_table} (dedupe_key) WHERE ((status IN ('queued', 'picked') AND dedupe_key IS NOT NULL));

    CREATE {durability_policy.queue_log_table} TABLE {self.settings.queue_table_log} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        job_id BIGINT NOT NULL,
        status {self.settings.queue_status_type} NOT NULL,
        priority INT NOT NULL,
        entrypoint TEXT NOT NULL,
        traceback JSONB DEFAULT NULL,
        aggregated BOOLEAN DEFAULT FALSE
    );
    CREATE INDEX {self.settings.queue_table_log}_not_aggregated ON {self.settings.queue_table_log} ((1)) WHERE not aggregated;
    CREATE INDEX {self.settings.queue_table_log}_created ON {self.settings.queue_table_log} (created);
    CREATE INDEX {self.settings.queue_table_log}_status ON {self.settings.queue_table_log} (status);
    CREATE INDEX {self.settings.queue_table_log}_job_id_status ON {self.settings.queue_table_log} (job_id, created DESC);

    CREATE {durability_policy.statistics_table} TABLE {self.settings.statistics_table} (
        id SERIAL PRIMARY KEY,
        created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT DATE_TRUNC('sec', NOW() at time zone 'UTC'),
        count BIGINT NOT NULL,
        priority INT NOT NULL,
        status {self.settings.queue_status_type} NOT NULL,
        entrypoint TEXT NOT NULL
    );
    CREATE UNIQUE INDEX {self.settings.statistics_table}_unique_count ON {self.settings.statistics_table} (
        priority,
        DATE_TRUNC('sec', created at time zone 'UTC'),
        status,
        entrypoint
    );

    CREATE {durability_policy.schedules_table} TABLE {self.settings.schedules_table} (
        id SERIAL PRIMARY KEY,
        expression TEXT NOT NULL, -- Crontab-like schedule definition (e.g., '* * * * *')
        entrypoint TEXT NOT NULL,
        heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        next_run TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        last_run TIMESTAMP WITH TIME ZONE,
        status {self.settings.queue_status_type} DEFAULT 'queued',
        UNIQUE (expression, entrypoint)
    );

    CREATE FUNCTION {self.settings.function}() RETURNS TRIGGER AS $$
    DECLARE
        to_emit BOOLEAN := false;  -- Flag to decide whether to emit a notification
    BEGIN
        -- Check operation type and set the emit flag accordingly
        IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
            to_emit := true;
        ELSIF TG_OP = 'DELETE' THEN
            to_emit := true;
        ELSIF TG_OP = 'INSERT' THEN
            to_emit := true;
        ELSIF TG_OP = 'TRUNCATE' THEN
            to_emit := true;
        END IF;

        -- Perform notification if the emit flag is set
        IF to_emit THEN
            PERFORM pg_notify(
                '{self.settings.channel}',
                json_build_object(
                    'channel', '{self.settings.channel}',
                    'operation', lower(TG_OP),
                    'sent_at', NOW(),
                    'table', TG_TABLE_NAME,
                    'type', 'table_changed_event'
                )::text
            );
        END IF;

        -- Return appropriate value based on the operation
        IF TG_OP IN ('INSERT', 'UPDATE') THEN
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NULL; -- For TRUNCATE and other non-row-specific contexts
        END IF;

    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER {self.settings.trigger}
    AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON {self.settings.queue_table}
    EXECUTE FUNCTION {self.settings.function}();
        """  # noqa: E501

    def build_uninstall_query(self) -> str:
        return f"""DROP TRIGGER    IF EXISTS   {self.settings.trigger} ON {self.settings.queue_table};
    DROP FUNCTION   IF EXISTS   {self.settings.function};
    DROP TABLE      IF EXISTS   {self.settings.queue_table};
    DROP TABLE      IF EXISTS   {self.settings.statistics_table};
    DROP TABLE      IF EXISTS   {self.settings.schedules_table};
    DROP TABLE      IF EXISTS   {self.settings.queue_table_log};
    DROP TYPE       IF EXISTS   {self.settings.queue_status_type};
    DROP TYPE       IF EXISTS   {add_prefix("pgqueuer_statistics_status")};
    """  # noqa

    def build_upgrade_queries(self) -> Generator[str, None, None]:
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();"  # noqa: E501
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table}_updated_id_id1_idx ON {self.settings.queue_table} (updated ASC, id DESC) INCLUDE (id) WHERE status = 'picked';"  # noqa: E501
        yield f"""CREATE OR REPLACE FUNCTION {self.settings.function}() RETURNS TRIGGER AS $$
    DECLARE
        to_emit BOOLEAN := false;  -- Flag to decide whether to emit a notification
    BEGIN
        -- Check operation type and set the emit flag accordingly
        IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
            to_emit := true;
        ELSIF TG_OP = 'DELETE' THEN
            to_emit := true;
        ELSIF TG_OP = 'INSERT' THEN
            to_emit := true;
        ELSIF TG_OP = 'TRUNCATE' THEN
            to_emit := true;
        END IF;

        -- Perform notification if the emit flag is set
        IF to_emit THEN
            PERFORM pg_notify(
                '{self.settings.channel}',
                json_build_object(
                    'channel', '{self.settings.channel}',
                    'operation', lower(TG_OP),
                    'sent_at', NOW(),
                    'table', TG_TABLE_NAME,
                    'type', 'table_changed_event'
                )::text
            );
        END IF;

        -- Return appropriate value based on the operation
        IF TG_OP IN ('INSERT', 'UPDATE') THEN
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NULL; -- For TRUNCATE and other non-row-specific contexts
        END IF;

    END;
    $$ LANGUAGE plpgsql;"""
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS heartbeat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();"  # noqa: E501
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table}_heartbeat_id_id1_idx ON {self.settings.queue_table} (heartbeat ASC, id DESC) INCLUDE (id) WHERE status = 'picked';"  # noqa: E501
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS queue_manager_id UUID;"  # noqa: E501
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table}_queue_manager_id_idx ON {self.settings.queue_table} (queue_manager_id) WHERE queue_manager_id IS NOT NULL;"  # noqa: E501
        yield f"""CREATE TABLE IF NOT EXISTS {self.settings.schedules_table} (
        id SERIAL PRIMARY KEY,
        expression TEXT NOT NULL, -- Crontab-like schedule definition (e.g., '* * * * *')
        entrypoint TEXT NOT NULL,
        heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        next_run TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        last_run TIMESTAMP WITH TIME ZONE,
        status {self.settings.queue_status_type} DEFAULT 'queued',
        UNIQUE (expression, entrypoint)
    );"""
        yield f"""ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS execute_after TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();"""  # noqa: E501
        yield f"ALTER TYPE {self.settings.queue_status_type} ADD VALUE IF NOT EXISTS 'successful';"  # noqa: E501
        yield f"ALTER TYPE {self.settings.queue_status_type} ADD VALUE IF NOT EXISTS 'exception';"  # noqa: E501
        yield f"ALTER TYPE {self.settings.queue_status_type} ADD VALUE IF NOT EXISTS 'canceled';"  # noqa: E501
        yield f"ALTER TYPE {self.settings.queue_status_type} ADD VALUE IF NOT EXISTS 'deleted';"  # noqa: E501
        yield f"ALTER TABLE {self.settings.statistics_table} ALTER COLUMN status TYPE {self.settings.queue_status_type} USING status::TEXT::pgqueuer_status;"  # noqa
        yield f"""CREATE UNLOGGED TABLE IF NOT EXISTS {self.settings.queue_table_log} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        job_id BIGINT NOT NULL,
        status {self.settings.queue_status_type} NOT NULL,
        priority INT NOT NULL,
        entrypoint TEXT NOT NULL,
        aggregated BOOLEAN DEFAULT FALSE
    );"""
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table_log}_not_aggregated ON {self.settings.queue_table_log} ((1)) WHERE not aggregated;"  # noqa
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table_log}_created ON {self.settings.queue_table_log} (created);"  # noqa
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table_log}_status ON {self.settings.queue_table_log} (status);"  # noqa
        yield f"ALTER TABLE {self.settings.queue_table_log} ADD COLUMN IF NOT EXISTS traceback JSONB DEFAULT NULL;"  # noqa: E501
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS dedupe_key TEXT DEFAULT NULL;"  # noqa: E501
        yield f"CREATE UNIQUE INDEX IF NOT EXISTS {self.settings.queue_table}_unique_dedupe_key ON {self.settings.queue_table} (dedupe_key) WHERE ((status IN ('queued', 'picked') AND dedupe_key IS NOT NULL));"  # noqa
        yield f"CREATE INDEX IF NOT EXISTS {self.settings.queue_table_log}_job_id_status ON {self.settings.queue_table_log} (job_id, created DESC);"  # noqa: E501
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS headers JSONB;"  # noqa: E501
        yield f"ALTER TABLE {self.settings.queue_table} ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0;"  # noqa: E501
        yield f"ALTER TYPE {self.settings.queue_status_type} ADD VALUE IF NOT EXISTS 'failed';"  # noqa: E501

    def build_table_has_column_query(self) -> str:
        return """SELECT EXISTS (
        SELECT FROM information_schema.columns
        WHERE
                table_schema = current_schema()
            AND table_name = $1
            AND column_name = $2
        );"""

    def build_table_has_index_query(self) -> str:
        return """SELECT EXISTS (
            SELECT 1
            FROM pg_indexes
            WHERE
                    tablename  = $1
                AND indexname  = $2
                AND schemaname = current_schema()
        );
        """

    def build_has_table_query(self) -> str:
        return """SELECT EXISTS (
        SELECT FROM information_schema.columns
        WHERE
                table_schema = current_schema()
            AND table_name = $1
        );"""

    def build_has_function_query(self) -> str:
        return """SELECT EXISTS (
            SELECT 1
            FROM pg_proc p
            JOIN pg_namespace n ON p.pronamespace = n.oid
            WHERE n.nspname = current_schema()
              AND p.proname = $1
        );"""

    def build_has_trigger_query(self) -> str:
        return """SELECT EXISTS (
            SELECT 1
            FROM pg_trigger t
            JOIN pg_class c ON t.tgrelid = c.oid
            JOIN pg_namespace n ON c.relnamespace = n.oid
            WHERE n.nspname = current_schema()
              AND t.tgname = $1
        );"""

    def build_user_types_query(self) -> str:
        return """SELECT enumlabel, typname
    FROM pg_enum
    JOIN pg_type ON pg_enum.enumtypid = pg_type.oid"""

    def build_alter_durability_query(self) -> Generator[str, None, None]:
        durability = self.settings.durability.config
        yield f"""ALTER TABLE {self.settings.queue_table} SET {"LOGGED" if durability.queue_table == "" else "UNLOGGED"};"""  # noqa
        yield f"""ALTER TABLE {self.settings.queue_table_log} SET {"LOGGED" if durability.queue_log_table == "" else "UNLOGGED"};"""  # noqa
        yield f"""ALTER TABLE {self.settings.statistics_table} SET {"LOGGED" if durability.statistics_table == "" else "UNLOGGED"};"""  # noqa
        yield f"""ALTER TABLE {self.settings.schedules_table} SET {"LOGGED" if durability.schedules_table == "" else "UNLOGGED"};"""  # noqa

    def build_optimize_autovacuum_query(self) -> str:
        return f"""ALTER TABLE {self.settings.queue_table} SET (
    autovacuum_vacuum_scale_factor   = 0.01,
    autovacuum_vacuum_threshold      = 1000,
    autovacuum_analyze_scale_factor  = 0.02,
    autovacuum_analyze_threshold     = 500,
    autovacuum_vacuum_cost_limit     = 10000,
    autovacuum_vacuum_cost_delay     = 0,
    fillfactor                       = 70
);

ALTER TABLE {self.settings.schedules_table} SET (
autovacuum_vacuum_scale_factor   = 0.01,
autovacuum_vacuum_threshold      = 1000,
autovacuum_analyze_scale_factor  = 0.02,
autovacuum_analyze_threshold     = 500,
autovacuum_vacuum_cost_limit     = 10000,
autovacuum_vacuum_cost_delay     = 0,
fillfactor                       = 70
);

ALTER TABLE {self.settings.queue_table_log} SET (
    autovacuum_vacuum_scale_factor   = 0.95,
    autovacuum_vacuum_threshold      = 1000000,
    autovacuum_analyze_scale_factor  = 0.05,
    autovacuum_analyze_threshold     = 10000
);

ALTER TABLE {self.settings.statistics_table} SET (
    autovacuum_vacuum_scale_factor   = 0.95,
    autovacuum_vacuum_threshold      = 1000000,
    autovacuum_analyze_scale_factor  = 0.05,
    autovacuum_analyze_threshold     = 10000
);"""

    def build_optimize_autovacuum_rollback_query(self) -> str:
        return f"""ALTER TABLE {self.settings.queue_table} RESET (
    autovacuum_vacuum_scale_factor,
    autovacuum_vacuum_threshold,
    autovacuum_analyze_scale_factor,
    autovacuum_analyze_threshold,
    autovacuum_vacuum_cost_limit,
    autovacuum_vacuum_cost_delay,
    fillfactor
);

ALTER TABLE {self.settings.schedules_table} RESET (
autovacuum_vacuum_scale_factor,
autovacuum_vacuum_threshold,
autovacuum_analyze_scale_factor,
autovacuum_analyze_threshold,
autovacuum_vacuum_cost_limit,
autovacuum_vacuum_cost_delay,
fillfactor
);

ALTER TABLE {self.settings.queue_table_log} RESET (
    autovacuum_vacuum_scale_factor,
    autovacuum_vacuum_threshold,
    autovacuum_analyze_scale_factor,
    autovacuum_analyze_threshold
);

ALTER TABLE {self.settings.statistics_table} RESET (
    autovacuum_vacuum_scale_factor,
    autovacuum_vacuum_threshold,
    autovacuum_analyze_scale_factor,
    autovacuum_analyze_threshold
);"""


@dataclasses.dataclass
class QueryQueueBuilder:
    settings: DBSettings = dataclasses.field(default_factory=DBSettings)

    def build_dequeue_query(self) -> str:
        t = self.settings.queue_table
        t_log = self.settings.queue_table_log
        return f"""WITH
-- Unpack per-entrypoint parameters.
-- effective_limit folds serialized (=1) and concurrency_limit into one
-- value; 0 means unlimited.
params AS (
    SELECT
        e.entrypoint,
        e.retry_after,
        CASE
            WHEN e.serialized             THEN 1
            WHEN e.concurrency_limit > 0  THEN e.concurrency_limit
            ELSE 0
        END AS effective_limit
    FROM (
        SELECT
            UNNEST($2::text[])     AS entrypoint,
            UNNEST($3::interval[]) AS retry_after,
            UNNEST($4::boolean[])  AS serialized,
            UNNEST($5::bigint[])   AS concurrency_limit
    ) e
),

-- Per-entrypoint count of picked jobs (global, all workers).
picked AS (
    SELECT entrypoint, COUNT(*) AS total
    FROM {t}
    WHERE queue_manager_id IS NOT NULL
      AND entrypoint = ANY($2)
    GROUP BY entrypoint
),

-- This worker's total picked jobs (scalar, for max_concurrent_tasks).
worker_load AS (
    SELECT COUNT(*) AS total
    FROM {t}
    WHERE queue_manager_id = $6
      AND entrypoint = ANY($2)
),

-- Eligible jobs: new (queued) or stale (picked past retry window).
eligible AS (
    SELECT q.id
    FROM {t} q
    JOIN      params p  ON p.entrypoint  = q.entrypoint
    LEFT JOIN picked pk ON pk.entrypoint = q.entrypoint
    WHERE q.execute_after < NOW()
      -- per-worker max-concurrent-tasks cap
      AND ($7::BIGINT IS NULL
           OR (SELECT total FROM worker_load) < $7)
      -- per-entrypoint concurrency (covers serialized too)
      AND (p.effective_limit = 0
           OR COALESCE(pk.total, 0) < p.effective_limit)
      -- queued jobs  OR  stale picked jobs eligible for retry
      AND (   q.status = 'queued'
           OR (    q.status = 'picked'
               AND p.retry_after > interval '0'
               AND q.heartbeat  < NOW() - p.retry_after))
    ORDER BY q.priority DESC, q.id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
),

-- Atomically claim the jobs and log the pick event.
claimed AS (
    UPDATE {t}
    SET status = 'picked',
        updated   = NOW(),
        heartbeat = NOW(),
        queue_manager_id = $6
    WHERE id IN (SELECT id FROM eligible)
    RETURNING *
),
log_pick AS (
    INSERT INTO {t_log} (job_id, status, entrypoint, priority)
    SELECT id, status, entrypoint, priority FROM claimed
)
SELECT * FROM claimed ORDER BY priority DESC, id ASC;
"""  # noqa

    def build_has_queued_work(self) -> str:
        return f"""
        SELECT
            COUNT(*) AS queued_work
        FROM
            {self.settings.queue_table}
        WHERE
                entrypoint = ANY($1)
            AND status = 'queued'
        """

    def build_enqueue_query(self) -> str:
        return f"""
        WITH inserted AS (
            INSERT INTO {self.settings.queue_table}
            (priority, entrypoint, payload, execute_after, dedupe_key, headers, status)
            VALUES (
                UNNEST($1::int[]),
                UNNEST($2::text[]),
                UNNEST($3::bytea[]),
                UNNEST($4::interval[]) + NOW(),
                UNNEST($5::text[]),
                UNNEST($6::jsonb[]),
                'queued'
            )
            RETURNING id, entrypoint, status, priority
        )
        INSERT INTO {self.settings.queue_table_log}
        (job_id, status, entrypoint, priority)
        SELECT id, 'queued', entrypoint, priority
        FROM inserted
        RETURNING job_id AS id
        """

    def build_delete_from_queue_query(self) -> str:
        return f"""WITH deleted AS (
            DELETE FROM {self.settings.queue_table}
            WHERE entrypoint = ANY($1)
            RETURNING id, entrypoint, priority
        )
        INSERT INTO {self.settings.queue_table_log} (job_id, status, entrypoint, priority)
        SELECT id, 'deleted'::{self.settings.queue_status_type} AS status, entrypoint, priority
        FROM deleted
        """

    def build_truncate_queue_query(self) -> str:
        return f"TRUNCATE {self.settings.queue_table}"

    def build_queue_size_query(self) -> str:
        return f"""SELECT
        count(*) AS count,
        priority,
        entrypoint,
        status
    FROM
        {self.settings.queue_table}
    GROUP BY entrypoint, priority, status
    ORDER BY count, entrypoint, priority, status
    """

    def build_log_job_query(self) -> str:
        return f"""WITH job_status AS (
            SELECT
                UNNEST($1::integer[])                           AS id,
                UNNEST($2::{self.settings.queue_status_type}[]) AS status,
                UNNEST($3::JSONB[])                             AS traceback
        ), deleted AS (
            DELETE FROM {self.settings.queue_table}
            WHERE id = ANY(SELECT js.id FROM job_status js WHERE js.status != 'failed')
            RETURNING id, entrypoint, priority
        ), held AS (
            UPDATE {self.settings.queue_table}
            SET status = 'failed', updated = NOW(), queue_manager_id = NULL
            WHERE id = ANY(SELECT js.id FROM job_status js WHERE js.status = 'failed')
            RETURNING id, entrypoint, priority
        ), all_resolved AS (
            SELECT id, entrypoint, priority FROM deleted
            UNION ALL
            SELECT id, entrypoint, priority FROM held
        ), merged AS (
            SELECT
                job_status.id           AS id,
                job_status.status       AS status,
                job_status.traceback    AS traceback,
                all_resolved.entrypoint AS entrypoint,
                all_resolved.priority   AS priority
            FROM job_status
            INNER JOIN all_resolved
                ON all_resolved.id = job_status.id
        )
        INSERT INTO {self.settings.queue_table_log} (
            job_id,
            status,
            entrypoint,
            priority,
            traceback
        )
        SELECT id, status, entrypoint, priority, traceback FROM merged
        """

    def build_truncate_log_statistics_query(self) -> str:
        return f"""TRUNCATE {self.settings.statistics_table}"""

    def build_delete_from_log_statistics_query(self) -> str:
        return f"""DELETE FROM {self.settings.statistics_table} WHERE entrypoint = ANY($1)"""

    def build_log_statistics_query(self) -> str:
        return f"""SELECT
        count,
        created,
        entrypoint,
        priority,
        status
    FROM {self.settings.statistics_table}
    WHERE ($2::interval IS NULL OR created > NOW() - $2)
    ORDER BY id DESC
    LIMIT $1
    """

    def build_notify_query(self) -> str:
        return f"""SELECT pg_notify('{self.settings.channel}', $1)"""

    def build_update_heartbeat_query(self) -> str:
        return f"""UPDATE {self.settings.queue_table} SET heartbeat = NOW() WHERE id = ANY($1::integer[])"""  # noqa: E501

    def build_truncate_log_query(self) -> str:
        return f"TRUNCATE {self.settings.queue_table_log}"

    def build_delete_log_query(self) -> str:
        return f"DELETE FROM {self.settings.queue_table_log} WHERE entrypoint = ANY($1)"

    def build_fetch_log_query(self) -> str:
        return f"SELECT * FROM {self.settings.queue_table_log}"

    def build_aggregate_log_data_to_statistics_query(self) -> str:
        return f"""WITH log_aggregation AS (
            SELECT
                entrypoint,
                priority,
                status,
                COUNT(*) AS count,
                date_trunc('sec', created) AS created
            FROM {self.settings.queue_table_log}
            WHERE NOT aggregated
            GROUP BY entrypoint, priority, status, date_trunc('sec', created)
        ),
        updated_logs AS (
            UPDATE {self.settings.queue_table_log}
            SET aggregated = TRUE
            WHERE NOT aggregated
            RETURNING id
        )
        INSERT INTO {self.settings.statistics_table} (count, created, entrypoint, priority, status)
        SELECT
            count,
            created,
            entrypoint,
            priority,
            status
        FROM log_aggregation
        ON CONFLICT (
            priority,
            date_trunc('sec', created AT TIME ZONE 'UTC'),
            status,
            entrypoint
        ) DO UPDATE SET
            count = {self.settings.statistics_table}.count + EXCLUDED.count
        """  # noqa

    def build_retry_job_query(self) -> str:
        return f"""WITH retry AS (
            UPDATE {self.settings.queue_table}
            SET
                status = 'queued',
                execute_after = NOW() + $2::interval,
                attempts = attempts + 1,
                updated = NOW(),
                queue_manager_id = NULL
            WHERE id = $1::integer
            RETURNING id, entrypoint, priority
        )
        INSERT INTO {self.settings.queue_table_log} (job_id, status, entrypoint, priority, traceback)
        SELECT id, 'queued', entrypoint, priority, $3::JSONB FROM retry
        """  # noqa: E501

    def build_requeue_jobs_query(self) -> str:
        return f"""WITH requeued AS (
            UPDATE {self.settings.queue_table}
            SET status = 'queued', execute_after = NOW(), updated = NOW(),
                attempts = 0, queue_manager_id = NULL
            WHERE id = ANY($1::integer[]) AND status = 'failed'
            RETURNING id, entrypoint, priority
        )
        INSERT INTO {self.settings.queue_table_log} (job_id, status, entrypoint, priority)
        SELECT id, 'queued', entrypoint, priority FROM requeued
        """

    def build_list_failed_jobs_query(self, order: SortOrder = "DESC") -> str:
        return f"""SELECT * FROM {self.settings.queue_table}
        WHERE status = 'failed'
        ORDER BY created {order}
        LIMIT $1
        """

    def build_queue_table_browse_query(self) -> str:
        return f"""SELECT * FROM {self.settings.queue_table}
        ORDER BY priority DESC, id ASC
        LIMIT $1 OFFSET $2
        """

    def build_failed_jobs_query(self) -> str:
        return f"""SELECT * FROM {self.settings.queue_table_log}
        WHERE status = 'exception'::{self.settings.queue_status_type}
        ORDER BY created DESC
        LIMIT $1
        """

    def build_queue_log_query(self) -> str:
        return f"""SELECT * FROM {self.settings.queue_table_log}
        ORDER BY created DESC
        LIMIT $1
        """

    def build_stale_jobs_query(self) -> str:
        return f"""SELECT id, priority, queue_manager_id, created, updated, heartbeat,
            execute_after, status, entrypoint,
            EXTRACT(EPOCH FROM NOW() - heartbeat) AS seconds_since_heartbeat
        FROM {self.settings.queue_table}
        WHERE status = 'picked'::{self.settings.queue_status_type}
          AND heartbeat < NOW() - $1::interval
        ORDER BY heartbeat ASC
        LIMIT $2
        """

    def build_queue_age_query(self) -> str:
        return f"""SELECT
            entrypoint,
            COUNT(*) AS queued_count,
            MIN(created) AS oldest_created,
            EXTRACT(EPOCH FROM NOW() - MIN(created)) AS oldest_age_seconds,
            AVG(EXTRACT(EPOCH FROM NOW() - created)) AS avg_age_seconds
        FROM {self.settings.queue_table}
        WHERE status = 'queued'::{self.settings.queue_status_type}
        GROUP BY entrypoint
        ORDER BY oldest_age_seconds DESC
        """

    def build_throughput_summary_query(self) -> str:
        return f"""SELECT
            entrypoint,
            status,
            SUM(count) AS total_count
        FROM {self.settings.statistics_table}
        WHERE ($1::interval IS NULL OR created > NOW() - $1)
        GROUP BY entrypoint, status
        ORDER BY entrypoint, status
        """

    def build_active_workers_query(self) -> str:
        return f"""SELECT
            queue_manager_id,
            COUNT(*) AS active_jobs,
            MIN(heartbeat) AS oldest_heartbeat,
            MAX(heartbeat) AS newest_heartbeat,
            array_agg(DISTINCT entrypoint) AS entrypoints
        FROM {self.settings.queue_table}
        WHERE status = 'picked'::{self.settings.queue_status_type}
          AND queue_manager_id IS NOT NULL
        GROUP BY queue_manager_id
        ORDER BY active_jobs DESC
        """

    def build_schema_info_query(self) -> str:
        return f"""SELECT
            c.relname AS table_name,
            CASE WHEN c.relpersistence = 'u' THEN 'UNLOGGED'
                 WHEN c.relpersistence = 'p' THEN 'LOGGED'
                 ELSE c.relpersistence::text
            END AS persistence,
            c.reltuples::bigint AS estimated_rows,
            pg_size_pretty(pg_total_relation_size(c.oid)) AS total_size
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = current_schema()
          AND c.relname IN (
            '{self.settings.queue_table}',
            '{self.settings.queue_table_log}',
            '{self.settings.statistics_table}',
            '{self.settings.schedules_table}'
          )
          AND c.relkind = 'r'
        ORDER BY c.relname
        """

    def build_job_status_query(self) -> str:
        return f"""SELECT DISTINCT ON (job_id) job_id, status
        FROM   {self.settings.queue_table_log}
        WHERE  job_id = ANY($1)
        ORDER  BY job_id, created DESC, id DESC;
        """

    def build_next_deferred_eta_query(self) -> str:
        return f"""SELECT MIN(execute_after) - NOW() AS eta
        FROM {self.settings.queue_table}
        WHERE status = 'queued'
          AND execute_after > NOW()
          AND entrypoint = ANY($1)
        """


@dataclasses.dataclass
class QuerySchedulerBuilder:
    settings: DBSettings = dataclasses.field(default_factory=DBSettings)

    def build_insert_schedule_query(self) -> str:
        return f"""WITH params AS (
        SELECT UNNEST($1::text[])       AS expression,
               UNNEST($2::text[])       AS entrypoint,
               UNNEST($3::interval[])   AS delay
        )
        INSERT INTO {self.settings.schedules_table} (expression, next_run, entrypoint)
        SELECT expression, date_trunc('seconds', NOW() + delay), entrypoint FROM params
        ON CONFLICT (entrypoint, expression) DO NOTHING"""

    def build_fetch_schedule_query(self) -> str:
        return f"""WITH params AS (
        SELECT UNNEST($1::text[])       AS expression,
               UNNEST($2::text[])       AS entrypoint,
               UNNEST($3::interval[])   AS delay
    ), picked_jobs AS (
        SELECT id, expression, entrypoint
        FROM {self.settings.schedules_table}
        WHERE
                ((entrypoint, expression) IN (SELECT entrypoint, expression FROM params)
            AND next_run <= NOW()
            AND status = 'queued')
            OR
                ((entrypoint, expression) IN (SELECT entrypoint, expression FROM params)
            AND NOW() - heartbeat > interval '30 seconds'
            AND status = 'picked')
        FOR UPDATE SKIP LOCKED
    )
    UPDATE {self.settings.schedules_table}
    SET
        status = 'picked',
        updated = NOW(),
        heartbeat = NOW(),
        next_run = date_trunc('seconds', NOW() + (
                SELECT delay FROM params
                WHERE
                    params.entrypoint = {self.settings.schedules_table}.entrypoint
                AND params.expression = {self.settings.schedules_table}.expression
            ))
    WHERE (entrypoint, expression) IN (SELECT entrypoint, expression FROM picked_jobs)
    RETURNING *;"""  # noqa: E501

    def build_set_schedule_queued_query(self) -> str:
        return f"""UPDATE {self.settings.schedules_table} SET status = 'queued', last_run = NOW(), updated = NOW() WHERE id = ANY($1);"""  # noqa: E501

    def build_update_schedule_heartbeat(self) -> str:
        return f"""UPDATE {self.settings.schedules_table} SET heartbeat = NOW(), updated = NOW() WHERE id = ANY($1);"""  # noqa: E501

    def build_peak_schedule_query(self) -> str:
        return f"""SELECT * FROM {self.settings.schedules_table} ORDER BY last_run ASC"""

    def build_delete_schedule_query(self) -> str:
        return f"""DELETE FROM {self.settings.schedules_table} WHERE id = ANY($1) OR entrypoint = ANY($2)"""  # noqa: E501

    def build_truncate_schedule_query(self) -> str:
        return f"""TRUNCATE {self.settings.schedules_table}"""
