"""Render the schema model as DDL, in the spelling ``pg_catalog`` reports back."""

from __future__ import annotations

from typing import Generator

from typing_extensions import assert_never

from pgqueuer.domain.schema.declaration import retired, target
from pgqueuer.domain.schema.model import (
    Column,
    EnumType,
    Function,
    Index,
    Schema,
    Table,
    Trigger,
)
from pgqueuer.domain.settings import DBSettings
from pgqueuer.domain.types import IndexName, TableName

try:
    from pgqueuer._version import version as VERSION
except ImportError:  # Source checkout without a build; the header says so.
    VERSION = "0.0.0"


def spelled(value: str, settings: DBSettings) -> str:
    """Qualify the status enum, which the model holds bare, for use in DDL."""
    if settings.db_schema is None:
        return value
    return value.replace(settings.queue_status_type, settings.qualified.queue_status_type)


def column_type(entry: Column) -> str:
    """Spelling for ``CREATE TABLE``: ``BIGSERIAL`` reports back as bigint plus a default."""
    if entry.kind == "plain":
        return entry.type
    if entry.kind == "serial":
        return "bigserial" if entry.type == "bigint" else "serial"
    if entry.kind == "identity":
        return f"{entry.type} GENERATED BY DEFAULT AS IDENTITY"
    assert_never(entry.kind)


def render_column(entry: Column, settings: DBSettings) -> str:
    parts = [entry.name, spelled(column_type(entry), settings)]
    if entry.not_null:
        parts.append("NOT NULL")
    if entry.default is not None:
        parts.append(f"DEFAULT {spelled(entry.default, settings)}")
    if entry.primary_key:
        parts.append("PRIMARY KEY")
    return " ".join(parts)


def render_table(entry: Table, settings: DBSettings, *, if_not_exists: bool = False) -> str:
    body = [render_column(column, settings) for column in entry.columns]
    body += [f"UNIQUE ({', '.join(unique.columns)})" for unique in entry.unique_constraints]
    persistence = "UNLOGGED TABLE" if entry.unlogged else "TABLE"
    guard = "IF NOT EXISTS " if if_not_exists else ""
    lines = ",\n".join(f"    {line}" for line in body)
    return f"CREATE {persistence} {guard}{settings.qualify(entry.name)} (\n{lines}\n);"


def render_index(entry: Index, settings: DBSettings, *, if_not_exists: bool = False) -> str:
    unique = "UNIQUE " if entry.unique else ""
    guard = "IF NOT EXISTS " if if_not_exists else ""
    table = settings.qualify(entry.table)
    return f"CREATE {unique}INDEX {guard}{entry.name} ON {table} {spelled(entry.body, settings)};"


def render_enum(entry: EnumType, settings: DBSettings) -> str:
    labels = ", ".join(f"'{label}'" for label in entry.labels)
    return f"CREATE TYPE {settings.qualify(entry.name)} AS ENUM ({labels});"


def render_function(entry: Function, settings: DBSettings, *, replace: bool = False) -> str:
    """``body`` is ``pg_proc.prosrc``: what sits between the dollar quotes."""
    create = "CREATE OR REPLACE FUNCTION" if replace else "CREATE FUNCTION"
    return (
        f"{create} {settings.qualify(entry.name)}() RETURNS TRIGGER AS "
        f"$${entry.body}$$ LANGUAGE plpgsql;"
    )


def render_trigger(entry: Trigger, settings: DBSettings) -> str:
    return (
        f"CREATE TRIGGER {entry.name}\n"
        f"AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON {settings.qualify(entry.table)}\n"
        f"EXECUTE FUNCTION {settings.qualify(entry.function)}();"
    )


def provenance(settings: DBSettings) -> str:
    """Names the release and the settings that shaped the statements below it."""
    return (
        f"-- pgqueuer {VERSION} -- prefix={settings.prefix!r} "
        f"schema={settings.db_schema!r} durability={settings.durability.value}"
    )


def render_install(settings: DBSettings, *, create_schema: bool = True) -> str:
    """Every object the current release declares, in dependency order."""
    schema = target(settings)
    statements = [provenance(settings)]
    if create_schema and settings.db_schema:
        statements.append(f"CREATE SCHEMA IF NOT EXISTS {settings.db_schema};")
    statements += [render_enum(entry, settings) for entry in schema.enums]
    statements += [render_table(entry, settings) for entry in schema.tables]
    statements += [render_index(entry, settings) for entry in schema.indexes]
    statements += [render_function(entry, settings) for entry in schema.functions]
    statements += [render_trigger(entry, settings) for entry in schema.triggers]
    return "\n\n".join(statements)


def render_uninstall(settings: DBSettings) -> str:
    """Drop what install created, dependents first, plus the retired types."""
    schema = target(settings)
    statements = [
        f"DROP TRIGGER IF EXISTS {entry.name} ON {settings.qualify(entry.table)};"
        for entry in schema.triggers
    ]
    statements += [
        f"DROP FUNCTION IF EXISTS {settings.qualify(entry.name)};" for entry in schema.functions
    ]
    statements += [
        f"DROP TABLE IF EXISTS {settings.qualify(entry.name)};" for entry in schema.tables
    ]
    statements += [f"DROP TYPE IF EXISTS {settings.qualify(entry.name)};" for entry in schema.enums]
    statements += [
        f"DROP TYPE IF EXISTS {settings.qualify(name)};" for name in retired(settings).types
    ]
    return "\n".join(statements)


def redefined_indexes(settings: DBSettings) -> tuple[IndexName, ...]:
    """Indexes redefined after they shipped, which ``IF NOT EXISTS`` cannot fix.

    Offline they are dropped and rebuilt by name; the planner reads the catalog.
    """
    return (
        # Shipped briefly as a 4-column composite before the revert.
        IndexName(f"{settings.queue_table_log}_not_aggregated"),
        # Keyed on time_in_queue before v0.19, and PG 14+ keeps the older
        # AT TIME ZONE spelling where the declaration says timezone().
        IndexName(f"{settings.statistics_table}_unique_count"),
    )


def converge_namespace(settings: DBSettings) -> Generator[str, None, None]:
    if settings.db_schema:
        yield f"CREATE SCHEMA IF NOT EXISTS {settings.db_schema};"


def converge_enums(schema: Schema, settings: DBSettings) -> Generator[str, None, None]:
    """``CREATE TYPE`` has no ``IF NOT EXISTS``, hence the exception block.

    Labels are one statement each: a value added by ``ALTER TYPE`` cannot be
    used in the transaction that added it.
    """
    for entry in schema.enums:
        yield (
            f"DO $$\nBEGIN\n    {render_enum(entry, settings)}\n"
            f"EXCEPTION\n    WHEN duplicate_object THEN NULL;\nEND $$;"
        )
        for label in entry.labels:
            yield f"ALTER TYPE {settings.qualify(entry.name)} ADD VALUE IF NOT EXISTS '{label}';"


def retirement_note(table: Table, settings: DBSettings) -> str:
    """Comment naming *table*'s retired columns, empty when it has none."""
    gone = [entry for entry in retired(settings).columns if entry.table == table.name]
    if not gone:
        return ""
    lines = ["-- No longer used by PgQueuer. Drop when you no longer need the data:"]
    lines += [
        f"--   ALTER TABLE {settings.qualify(table.name)} DROP COLUMN {entry.column};"
        for entry in gone
    ]
    return "\n".join(lines) + "\n"


def converge_tables(schema: Schema, settings: DBSettings) -> Generator[str, None, None]:
    """Create absent tables, then add absent plain columns to the rest.

    ``ADD COLUMN`` cannot introduce a serial primary key, and ``SET DEFAULT`` is
    catalog-only, so re-stating a default costs nothing and converges its spelling.
    """
    for table in schema.tables:
        qualified = settings.qualify(table.name)
        yield retirement_note(table, settings) + render_table(table, settings, if_not_exists=True)
        for column in table.columns:
            if column.kind != "plain":
                continue
            rendered_column = render_column(column, settings)
            yield f"ALTER TABLE {qualified} ADD COLUMN IF NOT EXISTS {rendered_column};"
            if column.default is not None:
                yield (
                    f"ALTER TABLE {qualified} ALTER COLUMN {column.name} "
                    f"SET DEFAULT {spelled(column.default, settings)};"
                )


def converge_retired_columns(settings: DBSettings) -> Generator[str, None, None]:
    """Relax NOT NULL on columns nothing has written since v0.19.

    Dropping them is not on the table: they hold data, so the constraint gives.
    """
    for entry in retired(settings).columns:
        yield f"""DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = {settings.schema_expr}
                 AND table_name = '{entry.table}'
                 AND column_name = '{entry.column}') THEN
        ALTER TABLE {settings.qualify(entry.table)}
            ALTER COLUMN {entry.column} DROP NOT NULL;
    END IF;
END $$;"""


def converge_statistics_status(settings: DBSettings) -> Generator[str, None, None]:
    """Move the statistics status column off its own pre-v0.27 enum."""
    status = settings.qualified.queue_status_type
    yield (
        f"ALTER TABLE {settings.qualified.statistics_table} "
        f"ALTER COLUMN status TYPE {status} USING status::TEXT::{status};"
    )


def converge_indexes(schema: Schema, settings: DBSettings) -> Generator[str, None, None]:
    gone = retired(settings).indexes + redefined_indexes(settings)
    for name in gone:
        yield f"DROP INDEX IF EXISTS {settings.qualify(name)};"
    for entry in schema.indexes:
        yield render_index(entry, settings, if_not_exists=True)


def converge_routines(schema: Schema, settings: DBSettings) -> Generator[str, None, None]:
    for function in schema.functions:
        yield render_function(function, settings, replace=True)
    for trigger in schema.triggers:
        yield f"DROP TRIGGER IF EXISTS {trigger.name} ON {settings.qualify(trigger.table)};"
        yield render_trigger(trigger, settings)


def widen_id_column(table: TableName, settings: DBSettings) -> str:
    """DO-guard on data_type keeps re-runs a no-op. *table* is a bare name."""
    return f"""DO $$
BEGIN
    IF (SELECT data_type FROM information_schema.columns
        WHERE table_schema = {settings.schema_expr}
          AND table_name = '{table}'
          AND column_name = 'id') = 'integer' THEN
        ALTER TABLE {settings.qualify(table)} ALTER COLUMN id TYPE BIGINT;
    END IF;
END $$;"""


def widen_id_sequence(table: TableName, settings: DBSettings) -> str:
    """Widen a legacy int4 sequence, which ``ALTER COLUMN TYPE`` leaves capped.

    ``AS BIGINT`` is a no-op on an already wide sequence, so it needs no guard.
    """
    return f"""DO $$
DECLARE
    seq TEXT := pg_get_serial_sequence('{settings.qualify(table)}', 'id');
BEGIN
    IF seq IS NOT NULL THEN
        EXECUTE format('ALTER SEQUENCE %s AS BIGINT', seq);
    END IF;
END $$;"""


def converge_id_width(schema: Schema, settings: DBSettings) -> Generator[str, None, None]:
    """Widen int4 id columns, which cap lifetime ids at ~2.1B.

    Gated: the rewrite takes ACCESS EXCLUSIVE, which a large table may not afford.
    """
    if not settings.widen_id:
        return
    for table in schema.tables:
        if any(column.kind == "serial" for column in table.columns):
            yield widen_id_column(table.name, settings)
            yield widen_id_sequence(table.name, settings)


def render_converge(settings: DBSettings) -> Generator[str, None, None]:
    """Statements bringing any earlier schema up to the declaration, offline.

    Blind to what is installed, so it creates and re-states rather than diffing;
    a connection gets the exact delta instead. Order is load-bearing: labels
    before the retype that uses them, columns before the indexes over them, and
    the retired type last, since a column references it until the retype runs.
    """
    schema = target(settings)
    yield from converge_namespace(settings)
    yield from converge_enums(schema, settings)
    yield from converge_tables(schema, settings)
    yield from converge_retired_columns(settings)
    yield from converge_statistics_status(settings)
    yield from converge_indexes(schema, settings)
    yield from converge_routines(schema, settings)
    yield from converge_id_width(schema, settings)
    for name in retired(settings).types:
        yield f"DROP TYPE IF EXISTS {settings.qualify(name)};"
