"""Render the schema model as DDL.

The model in :mod:`pgqueuer.domain.schema` is the only description of the
target shape; every statement here is derived from it. Definitions are emitted
in PostgreSQL's own canonical spelling, so what these renderers create reads
back from ``pg_catalog`` as what the model declares -- the property
``test_schema_inspect.py`` holds down.
"""

from __future__ import annotations

from typing_extensions import assert_never

from pgqueuer.domain.schema.declaration import retired, target
from pgqueuer.domain.schema.model import (
    Column,
    EnumType,
    Function,
    Index,
    Schema,
    Table,
    Trigger,
    resolve,
)
from pgqueuer.domain.settings import DBSettings
from pgqueuer.domain.types import TypeName

try:
    from pgqueuer._version import version as VERSION
except ImportError:  # Source checkout without a build; the header says so.
    VERSION = "0.0.0"


def rendered(settings: DBSettings) -> Schema:
    """The target schema with the status enum spelled as DDL must reference it.

    ``inspect()`` compares against the bare name; DDL needs the qualified one.
    """
    return resolve(target(settings), TypeName(settings.qualified.queue_status_type))


def column_type(entry: Column) -> str:
    """The type as written in ``CREATE TABLE``, which is not the reported type.

    A serial column reports ``bigint`` plus a ``nextval`` default; ``BIGSERIAL``
    is the shorthand that produces exactly that.
    """
    if entry.kind == "plain":
        return entry.type
    if entry.kind == "serial":
        return "bigserial" if entry.type == "bigint" else "serial"
    if entry.kind == "identity":
        return f"{entry.type} GENERATED BY DEFAULT AS IDENTITY"
    assert_never(entry.kind)


def render_column(entry: Column) -> str:
    parts = [entry.name, column_type(entry)]
    if entry.not_null:
        parts.append("NOT NULL")
    if entry.default is not None:
        parts.append(f"DEFAULT {entry.default}")
    if entry.primary_key:
        parts.append("PRIMARY KEY")
    return " ".join(parts)


def render_table(entry: Table, settings: DBSettings) -> str:
    body = [render_column(column) for column in entry.columns]
    body += [f"UNIQUE ({', '.join(unique.columns)})" for unique in entry.unique_constraints]
    persistence = "UNLOGGED TABLE" if entry.unlogged else "TABLE"
    lines = ",\n".join(f"    {line}" for line in body)
    return f"CREATE {persistence} {settings.qualify(entry.name)} (\n{lines}\n);"


def render_index(entry: Index, settings: DBSettings) -> str:
    unique = "UNIQUE " if entry.unique else ""
    table = settings.qualify(entry.table)
    return f"CREATE {unique}INDEX {entry.name} ON {table} {entry.body};"


def render_enum(entry: EnumType, settings: DBSettings) -> str:
    labels = ", ".join(f"'{label}'" for label in entry.labels)
    return f"CREATE TYPE {settings.qualify(entry.name)} AS ENUM ({labels});"


def render_function(entry: Function, settings: DBSettings) -> str:
    """``body`` is ``pg_proc.prosrc``: exactly what sits between the dollar quotes."""
    return (
        f"CREATE FUNCTION {settings.qualify(entry.name)}() RETURNS TRIGGER AS "
        f"$${entry.body}$$ LANGUAGE plpgsql;"
    )


def render_trigger(entry: Trigger, settings: DBSettings) -> str:
    return (
        f"CREATE TRIGGER {entry.name}\n"
        f"AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON {settings.qualify(entry.table)}\n"
        f"EXECUTE FUNCTION {settings.qualify(entry.function)}();"
    )


def provenance(settings: DBSettings) -> str:
    """Names the release and the settings that shaped the output below it.

    Saved as a migration file, the statements alone do not say which prefix or
    durability produced them.
    """
    return (
        f"-- pgqueuer {VERSION} -- prefix={settings.prefix!r} "
        f"schema={settings.db_schema!r} durability={settings.durability.value}"
    )


def render_install(settings: DBSettings, *, create_schema: bool = True) -> str:
    """Every object the current release declares, in dependency order."""
    schema = rendered(settings)
    statements = [provenance(settings)]
    if create_schema and settings.db_schema:
        statements.append(f"CREATE SCHEMA IF NOT EXISTS {settings.db_schema};")
    statements += [render_enum(entry, settings) for entry in schema.enums]
    statements += [render_table(entry, settings) for entry in schema.tables]
    statements += [render_index(entry, settings) for entry in schema.indexes]
    statements += [render_function(entry, settings) for entry in schema.functions]
    statements += [render_trigger(entry, settings) for entry in schema.triggers]
    return "\n\n".join(statements)


def render_uninstall(settings: DBSettings) -> str:
    """Drop what install created, dependents first, plus the retired types.

    Retired indexes and columns are not listed: their tables go with the rest.
    """
    schema = rendered(settings)
    statements = [
        f"DROP TRIGGER IF EXISTS {entry.name} ON {settings.qualify(entry.table)};"
        for entry in schema.triggers
    ]
    statements += [
        f"DROP FUNCTION IF EXISTS {settings.qualify(entry.name)};" for entry in schema.functions
    ]
    statements += [
        f"DROP TABLE IF EXISTS {settings.qualify(entry.name)};" for entry in schema.tables
    ]
    statements += [f"DROP TYPE IF EXISTS {settings.qualify(entry.name)};" for entry in schema.enums]
    statements += [
        f"DROP TYPE IF EXISTS {settings.qualify(name)};" for name in retired(settings).types
    ]
    return "\n".join(statements)
